"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# now import setuptools so it uses the monkeypatched methods
# Lets get things rolling
from setuptools import setup
from glob import glob

APP_NAME = 'TumblrThemr'
APP = ['src/main.py']
DATA_FILES = [ 
	('dialog',['src/dialog/bg.bmp']),
	('data',glob("src/data/*")),
	('templates',glob('src/templates/*'))
]
OPTIONS = {
	'argv_emulation': False,
	'includes':[ 'bottle', 'jinja2' ],
	'packages':[ 'dialog' ],
	'iconfile':'resources/Icon.icns'
}

setup(
    app=APP,
    name = APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
	package_dir = {'':'src/'}
)
