"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob

APP_NAME = 'tumblrtemplatr'
APP = ['src/main.py']
DATA_FILES = [ 
	('dialog',['src/dialog/bg.bmp']),
	('data',glob("src/data/*") )
]
OPTIONS = {
	'argv_emulation': False,
	'includes':[ 'bottle' ],
	'packages':[ 'dialog' ],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
	package_dir = {'':'src/'}
)
